apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: customer1-secrets
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "0095eecc-b256-469a-989f-5f250d201c4a"
    keyvaultName: "kv-apollo-staging"
    tenantId: "a591ace9-c2a4-491e-8153-9f9ae2cbee79"
    objects: |
      array:
        - |
          objectName: customer1-db-user
          objectType: secret
        - |
          objectName: customer1-db-password
          objectType: secret
  secretObjects:
    - secretName: customer1-db-credentials
      type: kubernetes.io/basic-auth
      data:
        - objectName: customer1-db-user
          key: username
        - objectName: customer1-db-password
          key: password
    - secretName: customer1-n8n-env
      type: Opaque
      data:
        - objectName: customer1-db-user
          key: DB_POSTGRESDB_USER
        - objectName: customer1-db-password
          key: DB_POSTGRESDB_PASSWORD
